/*O programa “Chamada da sala de aula” irá escrever o (primeiro) nome de todos os seus colegas, em ordem alfabética decrescente. Para ter acesso à lista dos nomes, você pode olhar a listagem da turma no Classroom. Dica: Para fazer a ordenação da lista na tela, utilize as teclas de atalho para "mover linhas” no VSCode.*/

/*Ainda não consegui fazer automático o cortar nome e o organizar, ainda...

var listaAluno = ["Carlos Alberto Rodrigues",
"Rafael Alves De Souza",
"Marcella Alzuguir",
"Marcos Antonio De Moraes Junior",
"Luana Aquino Da Silva",
"Angelita Arruda Sobrinho Zimbrão",
"Rodrigo Calmon Nogueira Da Gama Marques Fontes",
"Daniel Cesar da Costa",
"Viviane Dantas Soares",
"Rodrigo De Paula Ribeiro",
"Diego Dias Faria Da Silveira",
"Luciana Evangelista Dos Santos",
"Guilherme Ferreira Gusman",
"Leandro Fita",
"Luciana Gasparini Moreira Wendling",
"Nathan Guimarães",
"Higor Henrique Dos Santos Nascimento",
"Pedro Henrique Pinto Ricardo",
"Pedro Henrique Quaresma Coelho",
"Victor Hugo de Oliveira Martins",
"Gustavo Jardim De Barros",
"Karina Leal Da Silva",
"Gilnei Lima Dos Santos",
"Andre Luiz Curio Cintra",
"Adrian Menezes Da Silva",
"Samuel Miranda Ferreira",
"Raquel Nascimento Machado",
"Beatriz Neves Nolasco",
"Bruno Oliveira De Paula Salerno Ribeiro",
"Núria Peçanha Barbosa",
"Vanderson Pereira Da Silva",
"Eduardo Pina Brigatti",
"Gustavo Ponte Barbosa",
"Andre Ponte Da Silva",
"Matheus Rodrigues Andrade", 
"Marcos Vinicius Ferraz Gonçalves"]


var primeiroNome = listaAluno.split(" ", 1) //não funcinou para array*/

var primeiroNome = [
'Viviane',
'Victor',
'Vanderson',
'Samuel',
'Rodrigo',
'Rodrigo',
'Raquel',
'Rafael',
'Pedro',
'Pedro',
'Núria',
'Nathan',
'Matheus',
'Marcos',
'Marcos',
'Marcella',
'Luciana',
'Luciana',
'Luana',
'Leandro',
'Karina',
'Higor',
'Gustavo',
'Guilherme',
'Gilnei',
'Eduardo',
'Diego',
'Daniel',
'Carolina',
'Carlos',
'Bruno',
'Beatriz',
'Angelita',
'Andre',
'Andre',
'Adrian'
]

console.log(primeiroNome)

